---
- name: Instalar k3s
  hosts: k3s_node
  become: yes

  tasks:
    - name: Atualizar sistema
      apt:
        update_cache: yes
        upgrade: dist-upgrade

    - name: Instalar curl
      apt:
        name: curl
        state: present

    - name: Instalar k3s (método oficial)
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Habilitar e iniciar serviço k3s
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Verificar instalação
      command: k3s --version
      register: k3s_result
      changed_when: false

    - name: Mostrar resultado
      debug:
        msg: "K3s {{ k3s_result.stdout }} instalado com sucesso!"