---
- name: Instalar e configurar k3s
  hosts: all
  become: yes
  gather_facts: no  # Importante: desativar até ter Python

  pre_tasks:
    - name: Instalar Python3 (necessário para Ansible)
      apt:
        name: python3
        state: present
      when: ansible_os_family == 'Debian'

    - name: Configurar facts do Ansible
      setup:

  tasks:
    - name: Atualizar pacotes do sistema
      apt:
        update_cache: yes
        upgrade: dist-upgrade
        cache_valid_time: 3600

    - name: Instalar dependências
      apt:
        name:
          - curl
          - wget
          - tar
        state: present

    - name: Baixar o script de instalação do k3s
      get_url:
        url: https://get.k3s.io
        dest: /tmp/install-k3s.sh
        mode: '0755'

    - name: Instalar o k3s
      command: /tmp/install-k3s.sh
      args:
        creates: /usr/local/bin/k3s

    - name: Verificar status do k3s
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Verificar instalação
      command: k3s --version
      register: k3s_version
      changed_when: false

    - name: Mostrar versão do k3s
      debug:
        msg: "K3s instalado: {{ k3s_version.stdout }}"