---
- name: Instalar e configurar k3s
  hosts: all
  become: yes
  vars:
    ansible_user: "ubuntu"
  tasks:
    - name: Esperar que a instância esteja pronta
      ansible.builtin.wait_for_connection:
        timeout: 300
        delay: 10

    - name: Atualizar pacotes do sistema (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Instalar dependências (curl, etc)
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - wget
        - tar

    - name: Baixar o script de instalação do k3s
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/install-k3s.sh
        mode: '0755'

    - name: Instalar o k3s
      ansible.builtin.command: /tmp/install-k3s.sh
      args:
        creates: /usr/local/bin/k3s